
services:
  coredns_gslb:
    container_name: coredns_gslb
    image: ghcr.io/hrrrsn/coredns-gslb:${COREDNS_GSLB_VERSION:-latest}
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
      - "9153:9153/tcp"
      - "8080:8080/tcp"
    volumes:
      - ./coredns:/coredns
    command: -conf /Corefile
    env_file:
      - docker-example.env
    restart: always